import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const currentDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(currentDirectory, '..');
const templateDirectory = resolve(projectRoot, 'src', 'templates', 'legal');

const GENERATED_BANNER = '<!-- Generated by tools/sync-pages.mjs. Do not edit directly. -->';

const legalPages = [
    {
        outputFile: 'privacy.html',
        bodyClass: 'privacy-page',
        title: 'Zásady ochrany osobních údajů | Mykhailo Hyndriuk',
        description:
            'Podrobné zásady ochrany osobních údajů Mykhaila Hyndriuka – informace o sběru, zpracování a zabezpečení dat i o vašich právech podle GDPR.',
        subtitle: 'Zásady ochrany osobních údajů',
        heading: 'Zásady ochrany osobních údajů',
        navLinks: [
            { href: 'index.html#about', label: 'Zpět na hlavní stránku' },
            { href: 'index.html#contact-form-section', label: 'Nezávazná poptávka' },
        ],
        contentFile: 'privacy-content.html',
    },
    {
        outputFile: 'terms.html',
        bodyClass: 'terms-page',
        title: 'Obchodní podmínky | Mykhailo Hyndriuk',
        description:
            'Obchodní podmínky pro poskytování IT služeb, digitalizace a robotiky Mykhaila Hyndriuka – sjednávání smluv, ceny, platby i odpovědnost.',
        subtitle: 'Obchodní podmínky',
        heading: 'Obchodní podmínky',
        navLinks: [
            { href: 'index.html#about', label: 'Zpět na hlavní stránku' },
            { href: 'index.html#services', label: 'Služby' },
            { href: 'index.html#contact-form-section', label: 'Nezávazná poptávka' },
        ],
        contentFile: 'terms-content.html',
    },
];

const indent = (value, spaces) => {
    const prefix = ' '.repeat(spaces);

    return value
        .trim()
        .split('\n')
        .map((line) => `${prefix}${line}`)
        .join('\n');
};

const renderNavLinks = (navLinks) =>
    indent(navLinks.map(({ href, label }) => `<a href="${href}">${label}</a>`).join('\n'), 12);

const renderPage = (template, page, content) =>
    template
        .replace('{{title}}', page.title)
        .replace('{{description}}', page.description)
        .replace('{{body_class}}', page.bodyClass)
        .replace('{{subtitle}}', page.subtitle)
        .replace('{{heading}}', page.heading)
        .replace('{{nav_links}}', renderNavLinks(page.navLinks))
        .replace('{{content}}', indent(content, 12));

const syncLegalPages = async () => {
    const template = await readFile(resolve(templateDirectory, 'legal-shell.html'), 'utf8');

    for (const page of legalPages) {
        const content = await readFile(resolve(templateDirectory, page.contentFile), 'utf8');
        const outputPath = resolve(projectRoot, page.outputFile);
        const output = `${GENERATED_BANNER}\n${renderPage(template, page, content)}\n`;

        await writeFile(outputPath, output, 'utf8');
    }
};

const main = async () => {
    await syncLegalPages();
};

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
